apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: {{ env.RESULT_IMAGE }}
        name: result
        ports:
        - containerPort: 80
          name: result
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
  spec:
  type: NodePort
  selector:
    app: result
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
   