apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - image: 339713063356.dkr.ecr.us-west-1.amazonaws.com/vote-app-result:v1.0.16
        name: result
        ports:
        - containerPort: 80
          name: result
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: result-service
  labels:
    app: result
spec:
  type: ClusterIP
  selector:
    app: result
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    # nodePort: 31001

