apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: {{ env.VOTE_IMAGE }}
        name: vote
        ports:
        - containerPort: 80
          name: vote
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---

apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
  spec:
  type: NodePort
  selector:
    app: vote
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  
