apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - image: 339713063356.dkr.ecr.us-west-1.amazonaws.com/vote-app:v1.0.1
        name: vote
        ports:
        - containerPort: 80
          name: vote
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: vote-service
  labels:
    app: vote
spec:
  type: ClusterIP
  selector:
    app: vote
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    # nodePort: 31000

