apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ env.WORKER_IMAGE }}
        name: worker
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
