apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - image: 339713063356.dkr.ecr.us-west-1.amazonaws.com/vote-app-worker:v1.0.12
        name: worker
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
